### ISSUE TITLE
About login

### ISSUE THREAD

**Issue by smallrainbow** [mrowan137/tristan-mp-pu-master_densdecomp#1]
Hi,
I try to login the Princeton server following this guide 
https://ntoles.github.io/tristan-mp-pitp/Setting-up-ssh-keys#ssh-keys
I was blocked at ssh netID@perseus.princeton.edu
What shall I do, please? Thank you very much.
Best regards, Zhongwei

**Comment by mrowan137** [comment]
Hi Zhongwei, I do apologize for this late reply.  You will need to be part of that group to login to that server.
